introduced thread change flag  which needs changes in data_processor
LID-DS/LID-DS pull request #242
Opened 2021-11-08 15:13 UTC by boneymoy88

2021-11-09 11:14 UTC, alkor200 requested changes

2021-11-09 11:14 UTC, alkor200 commented on dataloader/data_preprocessor.py
> +        # print(syscall_feature_dict)
bitte zeile löschen

2021-11-09 11:14 UTC, alkor200 commented on algorithms/features/thread_change_flag.py
> +    def extract(self, syscall_features: dict, stream_features: dict) -> typing.Tuple[str, list]:
Signatur stimmt nicht mit BaseClass überein

2021-11-09 11:14 UTC, alkor200 commented on algorithms/features/thread_change_flag.py
> +    def extract(self, syscall_features: dict, stream_features: dict) -> typing.Tuple[str, list]:
Type hint auf Union mit None anpassen

2021-11-09 11:14 UTC, alkor200 commented on algorithms/features/thread_change_flag.py
> +    def _collect_features(self, stream_feature_dict: deque) -> list:
type hint dict nicht deque

2021-11-09 11:27 UTC, alkor200 commented
```
Could not load distinct syscalls. Calculating now...
     fitting features 2/2: 100%|██████████| 1/1 [00:00<00:00, 64527.75 features/s]
Calculating distinct syscalls: 100%|██████████| 210/210 [00:00<00:00, 238.25 recording/s]
Did not load Model Models/n2-e4-rFalsetcfFalse-tdFalse-ep20b128.
Training: 100%|██████████| 210/210 [00:02<00:00, 98.12 recording/s]
Traceback (most recent call last):
  File "/home/felix/repos/LID-DS/algorithms/ids_lstm_main.py", line 56, in <module>
    ids.train_decision_engine()
  File "/home/felix/repos/LID-DS/algorithms/ids.py", line 35, in train_decision_engine
    self._decision_engine.fit()
  File "/home/felix/repos/LID-DS/algorithms/decision_engines/lstm.py", line 147, in fit
    x_tensors_final = torch.reshape(x_tensors, (x_tensors.shape[0], 1, x_tensors.shape[1]))
IndexError: tuple index out of range

Process finished with exit code 1
```

2021-12-01 13:39 UTC, martingrimmer commented
@boneymoy88 ist das noch aktuell ?

2021-12-02 11:15 UTC, boneymoy88 commented
Closed because deprecated due to changes in IDS.

2021-12-02 11:15 UTC, closed without merging