Implemented CVE 2017 7529
LID-DS/LID-DS pull request #56
Opened 2021-04-30 12:18 UTC by Nirsi

2021-05-03 09:32 UTC, martingrimmer commented on scenarios/CVE-2017-7529/normal/Dockerfile
> +RUN pip3 install git+https://github.com/LID-DS/LID-DS@5d16ef9c539ac5323f0088e94ebb80a5cd00993a
wofür ist diese Zeile gut?

2021-05-03 09:34 UTC, martingrimmer commented on scenarios/CVE-2017-7529/normal/normal.py
> +    chrome_browser.get(url)
warum wird hier das Victim angefragt, bevor das erste Mal das Normalverhalten aufgerufen wird? Sollte eigentlich erst nach dem ersten mal `sys.stdin.readline()` passieren

2021-05-03 09:44 UTC, martingrimmer requested changes
* hab das Szenario ohne Angriff ausgeführt
* Da ist mMn etwas faul, denn es erzeugt auf meinem Host WLAN enorm Traffic!
* in der entstandenen scap konnte ich auch nur wenig Systemcalls finden (sysdig inspect genutzt) es wirkte so, als ob nur ein normalverhalten wirklich etwas tat und auch da nur am Anfang des Szenarios.

2021-05-03 12:17 UTC, Nirsi commented on scenarios/CVE-2017-7529/normal/Dockerfile
> +RUN pip3 install git+https://github.com/LID-DS/LID-DS@5d16ef9c539ac5323f0088e94ebb80a5cd00993a
good point, die kommt noch aus der alten Dockerfile. Wird entfernt

2021-05-03 12:54 UTC, Nirsi commented
@martingrimmer ich habe eine neue Version gepusht
Einzig das mit dem Traffic auf dem Host WLAN konnte ich nicht klären, habe aber bei mir monitored und keine außergewähnlichen Spitzen gesehen. Gleiche Ausschläge bekomme ich auch bei anderen Szenarien. Meine Vermutung ist, dass die verwendete unapp Fonts o.ä. aus dem Netz zieht. (Gleiche App kommt auch bei CVE-2014 und Bruteforce zum Einsatz)

2021-05-10 11:51 UTC, martingrimmer commented
Ein Aufruf der "unapp" hat direkt ordentlich Netzwerkanfragen ausgelöst. Man sieht auch gut wohin die so gingen.
Bist du dir sicher, dass das bei dir nicht passiert ist? Für das verhalten des Victims ist das aber eigentlich irrelevant. 
![screenshot](https://user-images.githubusercontent.com/17045229/117654761-7faa2580-b196-11eb-8124-e5585bbe04c1.png)


Ansonsten passt es jetzt aber.

2021-05-10 12:16 UTC, martingrimmer commented
eine Sache dazu noch: wenn zu viele User starten (es waren 20-25 voreingestellt) dann schaffen die jeweils nicht mehr als ein oder zwei Aktionen. Weil mein Host, einfach komplett mit denen ausgelastet war. Hier war es sehr hilfreich die Anzahl der User entsprechend zu reduzieren (5-10)

2021-05-10 12:20 UTC, merged